# This is a configuration for BitBucket Pipelines (For continuous integration).
# It does NOT means i did any work on unit test or integration test.
# 
image: gcc:6.1

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y cmake
          - mkdir build && cd $_
          - cmake ..
          - make
